//! Markdown reference-document generation (`docs/reference/<module>.md`).
//!
//! Human-diffable renderings of the specs for code review: changing a spec
//! shows up as a readable doc diff next to the generated schema diff.

use std::collections::BTreeMap;

use crate::model::{Arg, ArgTypeSpec, Interface, Module, Op, SpecSet};

/// Generate one markdown file per module (`<stem>.md`).
#[must_use]
pub fn generate_files(set: &SpecSet) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for m in &set.modules {
        let stem = m.name.strip_prefix("ldp.").unwrap_or(&m.name);
        out.insert(format!("{stem}.md"), gen_module(m));
    }
    out
}

fn gen_module(m: &Module) -> String {
    let mut o = String::new();
    pushln(
        &mut o,
        format!(
            "<!-- GENERATED by ldpc from spec/{}.toml — DO NOT EDIT. -->",
            stem(m)
        ),
    );
    o.push('\n');
    pushln(&mut o, format!("# Module `{}`\n", m.name));
    pushln(&mut o, format!("> {}\n", m.doc.replace('\n', " ")));
    let reqs: usize = m.interfaces.iter().map(|i| i.requests.len()).sum();
    let evs: usize = m.interfaces.iter().map(|i| i.events.len()).sum();
    pushln(
        &mut o,
        format!(
            "Version range **{}–{}** · {} interfaces · {} requests · {} events · {} enums · {} bitsets.\n",
            m.version_min,
            m.version_max,
            m.interfaces.len(),
            reqs,
            evs,
            m.enums.len(),
            m.bitsets.len()
        ),
    );

    if !m.enums.is_empty() {
        pushln(&mut o, "## Enums\n");
        for e in &m.enums {
            pushln(&mut o, format!("### `{}`\n", e.name));
            pushln(&mut o, format!("{}\n", e.doc.replace('\n', " ")));
            pushln(&mut o, "| Name | Value |");
            pushln(&mut o, "|---|---:|");
            for (n, v) in &e.values {
                pushln(&mut o, format!("| `{n}` | {v} |"));
            }
            o.push('\n');
        }
    }

    if !m.bitsets.is_empty() {
        pushln(&mut o, "## Bitsets\n");
        for b in &m.bitsets {
            pushln(&mut o, format!("### `{}`\n", b.name));
            pushln(&mut o, format!("{}\n", b.doc.replace('\n', " ")));
            pushln(&mut o, "| Bit | Index |");
            pushln(&mut o, "|---|---:|");
            for (n, i) in &b.bits {
                pushln(&mut o, format!("| `{n}` | {i} |"));
            }
            o.push('\n');
        }
    }

    pushln(&mut o, "## Interfaces\n");
    for i in &m.interfaces {
        gen_interface(&mut o, m, i);
    }
    o
}

fn gen_interface(o: &mut String, m: &Module, i: &Interface) {
    pushln(o, format!("### `{}.{}`\n", m.name, i.name));
    pushln(o, format!("{}\n", i.doc.replace('\n', " ")));
    let mut meta = vec![];
    if i.global {
        meta.push("global (registry-advertised)".to_string());
    }
    if let Some(id) = i.builtin_id {
        meta.push(format!("builtin ID {id}"));
    }
    if !meta.is_empty() {
        pushln(o, format!("*{}*\n", meta.join(" · ")));
    }
    gen_ops(o, "Requests", &i.requests, true);
    gen_ops(o, "Events", &i.events, false);
}

fn gen_ops(o: &mut String, title: &str, ops: &[Op], is_request: bool) {
    if ops.is_empty() {
        return;
    }
    pushln(o, format!("#### {title}\n"));
    pushln(
        o,
        if is_request {
            "| Opcode | Name | Since | Reply | Arguments |".to_string()
        } else {
            "| Opcode | Name | Since | Arguments |".to_string()
        },
    );
    pushln(
        o,
        if is_request {
            "|---:|---|---:|---|---|".to_string()
        } else {
            "|---:|---|---:|---|".to_string()
        },
    );
    for (idx, op) in ops.iter().enumerate() {
        let args: Vec<String> = op.args.iter().map(arg_cell).collect();
        let args = if args.is_empty() {
            "—".to_string()
        } else {
            args.join(", ")
        };
        let reply = if is_request {
            format!(
                " {} |",
                op.reply
                    .as_deref()
                    .map_or("—".to_string(), |r| format!("`{r}`"))
            )
        } else {
            String::new()
        };
        pushln(
            o,
            format!(
                "| {} | `{}` | {} |{reply} {args} |",
                idx + 1,
                op.name,
                op.since
            ),
        );
    }
    o.push('\n');
    let with_docs: Vec<(String, String)> = op_arg_docs(ops);
    if !with_docs.is_empty() {
        for (name, doc) in with_docs {
            pushln(o, format!("* `{name}` — {}", doc.replace('\n', " ")));
        }
        o.push('\n');
    }
}

fn op_arg_docs(ops: &[Op]) -> Vec<(String, String)> {
    let mut out = vec![];
    for op in ops {
        for a in &op.args {
            if !a.doc.is_empty() {
                out.push((format!("{}.{}", op.name, a.name), a.doc.clone()));
            }
        }
    }
    out
}

fn arg_cell(a: &Arg) -> String {
    let ty = match (&a.of, a.ty) {
        (Some(of), ArgTypeSpec::Enum | ArgTypeSpec::Bitset) => format!("{}<{of}>", a.ty.as_str()),
        (Some(of), ArgTypeSpec::Array) => format!("array<{of}>"),
        (Some(of), ArgTypeSpec::Object | ArgTypeSpec::NewId) => {
            format!(
                "{}<{of}>{}",
                a.ty.as_str(),
                if a.nullable { "?" } else { "" }
            )
        }
        (None, ArgTypeSpec::Object) if a.nullable => "object?".to_string(),
        _ => a.ty.as_str().to_string(),
    };
    format!("`{}: {ty}`", a.name)
}

fn stem(m: &Module) -> &str {
    m.name.strip_prefix("ldp.").unwrap_or(&m.name)
}

fn pushln(o: &mut String, s: impl AsRef<str>) {
    o.push_str(s.as_ref());
    o.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_doc_shape() {
        let set = crate::testutil::fixture_set();
        let files = generate_files(&set);
        let md = &files["t.md"];
        assert!(md.starts_with("<!-- GENERATED by ldpc"));
        assert!(md.contains("# Module `ldp.t`"));
        assert!(md.contains("### `st`"));
        assert!(md.contains("| `off` | 1 |"));
        assert!(md.contains("### `ldp.t.thing`"));
        assert!(md.contains("#### Requests"));
        assert!(md.contains("| 1 | `poke` | 1 | `poked` | `n: uint32` |"));
        assert!(md.contains("#### Events"));
        assert!(md.contains("`s: enum<st>`"));
        assert_eq!(md, &generate_files(&set)["t.md"]);
    }
}
