//! Rust schema-code generation (`crates/ldp-protocol/src/generated/`).
//!
//! One file per module plus `mod.rs`, per the Phase 2 contract in
//! `docs/spec-format.md` §5: static `ModuleSchema` tables (as compiled by
//! `ldp-protocol`), typed `#[non_exhaustive]` enums, bitset const modules,
//! opcode constants, and rustdoc taken verbatim from the spec `doc`
//! fields. Output is byte-stable (sorted, no timestamps) so drift
//! detection is exact.

use std::collections::BTreeMap;

use crate::model::{ArgTypeSpec, BitsetDef, EnumDef, Interface, Module, Op, SpecSet};
use crate::names::{escape_ident, rustdoc_escape, str_lit, to_camel, to_upper_snake};

/// Generate every Rust file: `mod.rs` plus `<stem>.rs` per module.
#[must_use]
pub fn generate_files(set: &SpecSet) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    out.insert("mod.rs".to_string(), gen_root(set));
    for m in &set.modules {
        let stem = stem_of(m);
        out.insert(format!("{stem}.rs"), gen_module(m));
    }
    out
}

fn stem_of(m: &Module) -> &str {
    m.name.strip_prefix("ldp.").unwrap_or(&m.name)
}

fn gen_root(set: &SpecSet) -> String {
    let mut o = Out::new();
    o.line("//! GENERATED by ldpc from `spec/*.toml` — DO NOT EDIT.");
    o.line("//!");
    o.line("//! This module and its children are compiler output: edit `spec/*.toml`, then");
    o.line("//! regenerate with `cargo run -p ldpc -- gen`. CI regenerates and fails on drift");
    o.line("//! (`docs/roadmap.md` Phase 2 exit criteria). Hand edits are overwritten.");
    o.line("");
    o.line("// Generated tables are deliberately not rustfmt-formatted: this layout is the");
    o.line("// compiler's output format, byte-stable for drift detection.");
    for m in &set.modules {
        o.line("#[rustfmt::skip]");
        o.line(format!("pub mod {};", escape_ident(stem_of(m))));
    }
    o.line("");
    o.line("use crate::schema::ModuleSchema;");
    o.line("");
    o.doc(
        "",
        "The compiled introspection blob: the spec re-serialized for runtime tooling \
         (parsed by `crate::blob`; served to clients via `registry.schema`).",
    );
    o.line("pub const BLOB: &[u8] = include_bytes!(\"blob.bin\");");
    o.line("");
    o.doc(
        "",
        "Every module schema compiled into this build, sorted by module name.",
    );
    let refs: Vec<String> = set
        .modules
        .iter()
        .map(|m| format!("&{}::MODULE", escape_ident(stem_of(m))))
        .collect();
    let one_line = format!(
        "pub static MODULES: &[&ModuleSchema] = &[{}];",
        refs.join(", ")
    );
    // Emit the rustfmt-stable shape directly: single line when it fits,
    // one entry per line otherwise (mod.rs itself IS formatted).
    if one_line.len() <= 100 {
        o.line(one_line);
    } else {
        o.line("pub static MODULES: &[&ModuleSchema] = &[");
        for m in &set.modules {
            o.line(format!("    &{}::MODULE,", escape_ident(stem_of(m))));
        }
        o.line("];");
    }
    o.finish()
}

fn gen_module(m: &Module) -> String {
    let mut o = Out::new();
    let stem = stem_of(m);
    o.line(format!(
        "//! GENERATED by ldpc from `spec/{stem}.toml` — DO NOT EDIT."
    ));
    o.line("//!");
    o.line("//! Regenerate with `cargo run -p ldpc -- gen`; CI fails on drift.");
    o.line("");
    o.line("#![allow(clippy::all, clippy::pedantic, clippy::nursery)]");
    o.line("#![allow(unused_imports, unused_qualifications, rust_2018_idioms)]");
    o.line("");
    o.line("use crate::schema::{ArgSchema, BitsetDef, EnumDef, InterfaceSchema, ModuleSchema, OpSchema};");
    o.line("use ldp_core::wire::ArgType;");
    o.line("");
    for e in &m.enums {
        gen_enum(&mut o, e);
    }
    for b in &m.bitsets {
        gen_bitset(&mut o, b);
    }
    for i in &m.interfaces {
        gen_interface(&mut o, m, i);
    }
    o.doc("", &m.doc);
    let ifaces: Vec<String> = m
        .interfaces
        .iter()
        .map(|i| format!("&{}::SCHEMA", escape_ident(&i.name)))
        .collect();
    let enums: Vec<String> = m
        .enums
        .iter()
        .map(|e| format!("&{}_DEF", to_upper_snake(&e.name)))
        .collect();
    let bitsets: Vec<String> = m
        .bitsets
        .iter()
        .map(|b| format!("&{}::DEF", escape_ident(&b.name)))
        .collect();
    o.line("pub const MODULE: ModuleSchema = ModuleSchema {");
    o.line(format!("    name: {},", str_lit(&m.name)));
    o.line(format!("    version_min: {},", m.version_min));
    o.line(format!("    version_max: {},", m.version_max));
    o.line(format!("    doc: {},", str_lit(&m.doc)));
    o.line(format!("    interfaces: &[{}],", ifaces.join(", ")));
    o.line(format!("    enums: &[{}],", enums.join(", ")));
    o.line(format!("    bitsets: &[{}],", bitsets.join(", ")));
    o.line("};");
    o.line("");
    o.finish()
}

fn gen_enum(o: &mut Out, e: &EnumDef) {
    let ty = to_camel(&e.name);
    let values_const = format!("{}_VALUES", to_upper_snake(&e.name));
    let def_const = format!("{}_DEF", to_upper_snake(&e.name));
    o.doc("", &e.doc);
    o.line("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]");
    o.line("#[non_exhaustive]");
    o.line(format!("pub enum {ty} {{"));
    for (vname, v) in &e.values {
        o.doc("    ", format!("`{vname}` = {v}."));
        o.line(format!("    {},", to_camel(vname)));
    }
    o.line("}");
    o.line("");
    o.line(format!("impl {ty} {{"));
    o.doc("    ", "The wire value of this variant.");
    o.line("    #[must_use]");
    o.line("    pub const fn to_wire(self) -> u32 {");
    o.line("        match self {");
    for (vname, v) in &e.values {
        o.line(format!("            Self::{} => {v},", to_camel(vname)));
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    o.doc(
        "    ",
        "The variant for a wire value, or `None` when this build does not know it",
    );
    o.doc(
        "    ",
        "(unknown values are tolerated for forward compatibility — `docs/spec-format.md` §4).",
    );
    o.line("    #[must_use]");
    o.line("    pub const fn from_wire(value: u32) -> Option<Self> {");
    o.line("        match value {");
    for (vname, v) in &e.values {
        o.line(format!(
            "            {v} => Some(Self::{}),",
            to_camel(vname)
        ));
    }
    o.line("            _ => None,");
    o.line("        }");
    o.line("    }");
    o.line("}");
    o.line("");
    o.doc(
        "",
        format!("(name, wire value) pairs of `{}`, sorted by value.", e.name),
    );
    let pairs: Vec<String> = e
        .values
        .iter()
        .map(|(n, v)| format!("({}, {v})", str_lit(n)))
        .collect();
    o.line(format!(
        "pub const {values_const}: &[(&str, u32)] = &[{}];",
        pairs.join(", ")
    ));
    o.line("");
    o.doc(
        "",
        format!("Schema-table definition of the `{}` enum.", e.name),
    );
    o.line(format!("pub const {def_const}: EnumDef = EnumDef {{"));
    o.line(format!("    name: {},", str_lit(&e.name)));
    o.line(format!("    doc: {},", str_lit(&e.doc)));
    o.line(format!("    values: {values_const},"));
    o.line("};");
    o.line("");
}

fn gen_bitset(o: &mut Out, b: &BitsetDef) {
    let module = escape_ident(&b.name);
    o.doc("", format!("Named bits of `{}`: {}", b.name, b.doc));
    o.line(format!("pub mod {module} {{"));
    o.line("    use crate::schema::BitsetDef;");
    o.line("");
    for (bname, idx) in &b.bits {
        o.doc("    ", format!("Bit `{bname}` (index {idx})."));
        o.line(format!(
            "    pub const {}: u128 = 1u128 << {idx};",
            to_upper_snake(bname)
        ));
    }
    if b.bits.is_empty() {
        o.line("");
    }
    o.doc("    ", "Union of every declared bit.");
    let mask: Vec<String> = b
        .bits
        .iter()
        .map(|&(_, i)| format!("1u128 << {i}"))
        .collect();
    let mask = if mask.is_empty() {
        "0u128".to_string()
    } else {
        mask.join(" | ")
    };
    o.line(format!("    pub const MASK: u128 = {mask};"));
    o.doc(
        "    ",
        format!("(name, bit index) pairs of `{}`, sorted by index.", b.name),
    );
    let pairs: Vec<String> = b
        .bits
        .iter()
        .map(|(n, i)| format!("({}, {i})", str_lit(n)))
        .collect();
    o.line(format!(
        "    pub const BITS: &[(&str, u32)] = &[{}];",
        pairs.join(", ")
    ));
    o.doc(
        "    ",
        format!("Schema-table definition of the `{}` bitset.", b.name),
    );
    o.line("    pub const DEF: BitsetDef = BitsetDef {");
    o.line(format!("        name: {},", str_lit(&b.name)));
    o.line(format!("        doc: {},", str_lit(&b.doc)));
    o.line("        bits: BITS,");
    o.line("    };");
    o.line("}");
    o.line("");
}

fn gen_interface(o: &mut Out, m: &Module, i: &Interface) {
    let fq = format!("{}.{}", m.name, i.name);
    let module = escape_ident(&i.name);
    o.doc("", &i.doc);
    o.line(format!("pub mod {module} {{"));
    o.line("    use crate::schema::{ArgSchema, InterfaceSchema, OpSchema};");
    o.line("    use ldp_core::wire::ArgType;");
    o.line("");
    o.doc("    ", "Fully qualified interface name.");
    o.line(format!("    pub const NAME: &str = {};", str_lit(&fq)));
    o.doc(
        "    ",
        "Minimum wire version (the module's advertised range).",
    );
    o.line(format!(
        "    pub const VERSION_MIN: u32 = {};",
        m.version_min
    ));
    o.doc(
        "    ",
        "Maximum wire version (the module's advertised range).",
    );
    o.line(format!(
        "    pub const VERSION_MAX: u32 = {};",
        m.version_max
    ));
    o.doc(
        "    ",
        "Complete schema: identity, version range, request and event signatures.",
    );
    o.line("    pub const SCHEMA: InterfaceSchema = InterfaceSchema {");
    o.line("        name: NAME,");
    o.line("        version_min: VERSION_MIN,");
    o.line("        version_max: VERSION_MAX,");
    o.line(format!("        doc: {},", str_lit(&i.doc)));
    o.line(format!("        global: {},", i.global));
    o.line(format!(
        "        builtin_id: {},",
        match i.builtin_id {
            Some(id) => format!("Some({id})"),
            None => "None".to_string(),
        }
    ));
    o.line("        requests: REQUESTS,");
    o.line("        events: EVENTS,");
    o.line("    };");
    o.line("");
    gen_opcodes(o, "request", &i.requests);
    gen_opcodes(o, "event", &i.events);
    gen_op_table(
        o,
        "REQUESTS",
        "Request signatures, opcode order.",
        &i.requests,
    );
    gen_op_table(o, "EVENTS", "Event signatures, opcode order.", &i.events);
    o.line("}");
    o.line("");
}

fn gen_opcodes(o: &mut Out, kind: &str, ops: &[Op]) {
    o.doc(
        "    ",
        format!(
            "{} opcodes — declaration order, contiguous from 1, frozen once released.",
            if kind == "request" {
                "Request"
            } else {
                "Event"
            }
        ),
    );
    o.line(format!("    pub mod {kind} {{"));
    if ops.is_empty() {
        o.line("        //! This interface declares no operations of this kind.");
    }
    for (idx, op) in ops.iter().enumerate() {
        let opcode = idx + 1;
        o.doc(
            "        ",
            format!("Opcode {opcode}: `{}` (since {}).", op.name, op.since),
        );
        o.line(format!(
            "        pub const {}: u32 = {opcode};",
            to_upper_snake(&op.name)
        ));
    }
    o.line("    }");
    o.line("");
}

fn gen_op_table(o: &mut Out, const_name: &str, doc: &str, ops: &[Op]) {
    o.doc("    ", doc);
    o.line(format!("    const {const_name}: &[OpSchema] = &["));
    for (idx, op) in ops.iter().enumerate() {
        let opcode = idx + 1;
        o.line("        OpSchema {");
        o.line(format!("            name: {},", str_lit(&op.name)));
        o.line(format!("            opcode: {opcode},"));
        o.line(format!("            since: {},", op.since));
        o.line(format!("            doc: {},", str_lit(&op.doc)));
        o.line(format!(
            "            reply: {},",
            match &op.reply {
                Some(r) => format!("Some({})", str_lit(r)),
                None => "None".to_string(),
            }
        ));
        o.line("            args: &[");
        for a in &op.args {
            o.line("                ArgSchema {");
            o.line(format!("                    name: {},", str_lit(&a.name)));
            o.line(format!(
                "                    ty: ArgType::{},",
                arg_ty_token(a.ty)
            ));
            o.line(format!(
                "                    of: {},",
                match &a.of {
                    Some(x) => format!("Some({})", str_lit(x)),
                    None => "None".to_string(),
                }
            ));
            o.line(format!("                    nullable: {},", a.nullable));
            o.line(format!("                    doc: {},", str_lit(&a.doc)));
            o.line("                },");
        }
        o.line("            ],");
        o.line("        },");
    }
    o.line("    ];");
    o.line("");
}

fn arg_ty_token(t: ArgTypeSpec) -> &'static str {
    match t {
        ArgTypeSpec::Int32 => "Int32",
        ArgTypeSpec::Uint32 => "Uint32",
        ArgTypeSpec::Int64 => "Int64",
        ArgTypeSpec::Uint64 => "Uint64",
        ArgTypeSpec::Float32 => "Float32",
        ArgTypeSpec::Float64 => "Float64",
        ArgTypeSpec::Bool => "Bool",
        ArgTypeSpec::String => "String",
        ArgTypeSpec::Ts => "Ts",
        ArgTypeSpec::Rect => "Rect",
        ArgTypeSpec::Object => "Object",
        ArgTypeSpec::NewId => "NewId",
        ArgTypeSpec::Fd => "Fd",
        ArgTypeSpec::Array => "Array",
        ArgTypeSpec::Enum => "Enum",
        ArgTypeSpec::Bitset => "Bitset",
    }
}

/// Line emitter with doc-comment helpers (rustdoc-escaped).
struct Out {
    lines: Vec<String>,
}

impl Out {
    fn new() -> Self {
        Out { lines: Vec::new() }
    }

    fn line(&mut self, s: impl Into<String>) {
        self.lines.push(s.into());
    }

    /// `///` doc lines from spec prose (trimmed, rustdoc-escaped), emitted
    /// with the given indentation.
    fn doc(&mut self, indent: &str, text: impl AsRef<str>) {
        let text = text.as_ref().trim();
        if text.is_empty() {
            self.lines.push(format!("{indent}///"));
            return;
        }
        for l in text.split('\n') {
            let l = l.trim_end();
            if l.is_empty() {
                self.lines.push(format!("{indent}///"));
            } else {
                self.lines
                    .push(format!("{indent}/// {}", rustdoc_escape(l)));
            }
        }
    }

    fn finish(self) -> String {
        let mut s = self.lines.join("\n");
        s.push('\n');
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arg_type_tokens_are_exhaustive_and_match_spec_names() {
        for spec_name in [
            "int32", "uint32", "int64", "uint64", "float32", "float64", "bool", "string", "ts",
            "rect", "object", "new_id", "fd", "array", "enum", "bitset",
        ] {
            let t = ArgTypeSpec::parse(spec_name).unwrap();
            assert_eq!(t.as_str(), spec_name);
            assert!(arg_ty_token(t).chars().any(|c| c.is_ascii_uppercase()));
            assert!((0x01..=0x10).contains(&t.wire_tag()));
        }
    }

    #[test]
    fn generated_root_has_all_modules_and_blob() {
        let set = crate::testutil::fixture_set();
        let files = generate_files(&set);
        assert!(files.contains_key("mod.rs"));
        let root = &files["mod.rs"];
        assert!(root.contains("#[rustfmt::skip]"));
        assert!(root.contains("pub mod t;"));
        assert!(root.contains("include_bytes!(\"blob.bin\")"));
        assert!(root.contains("pub static MODULES: &[&ModuleSchema] = &[&t::MODULE];"));
    }

    #[test]
    fn generated_module_shape() {
        let set = crate::testutil::fixture_set();
        let files = generate_files(&set);
        let m = &files["t.rs"];
        assert!(m.contains("pub enum St {"));
        assert!(m.contains("pub const ST_VALUES: &[(&str, u32)]"));
        assert!(m.contains("pub const ST_DEF: EnumDef"));
        assert!(m.contains("pub mod caps {"));
        assert!(m.contains("pub const MASK: u128"));
        assert!(m.contains("pub mod thing {"));
        assert!(m.contains("pub mod request {"));
        assert!(m.contains("pub const POKE: u32 = 1;"));
        assert!(m.contains("const REQUESTS: &[OpSchema] = &["));
        assert!(m.contains("ty: ArgType::Uint32"));
        assert!(m.contains("of: Some(\"st\")"));
        assert!(m.contains("doc: \"A thing.\""));
        // Byte-stable: two runs produce identical output.
        assert_eq!(m, &generate_files(&set)["t.rs"]);
    }
}
